import StockApi from "./components/StockSearch";
import React, { useState } from "react";
import Card from "./components/Card";

function App() {
  const [stockData, setStockData] = useState([]);
  const getStockData = (newStock, isAutoGenerated) => {
    for (const index in stockData) {
      if (!isAutoGenerated && newStock.Ticker === stockData[index].Ticker) {
        alert(newStock.Ticker + " is already on your list!");
        return;
      } else if (newStock.Ticker === stockData[index].Ticker) {
        return;
      }
    }
    setStockData((prev) => {
      console.log("Prev", prev);
      return [...prev, newStock];
    });
  };

  return (
    <React.Fragment>
      <StockApi getStockData={getStockData} />
      <Card stockData={stockData} onStockChange={setStockData} />
    </React.Fragment>
  );
}

export default App;
